import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/theme-provider'
import Sidebar from '@/components/Sidebar'
import { cn } from '@/lib/utils'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <ThemeProvider
        attribute="class"
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange
      >
      <html lang="en" suppressHydrationWarning>
        <body className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased bg-secondary`,

          )}>
          <Navbar />
          <div className='hidden md:flex mt-16 w-20 flex-col fixed inset-y-0'>
            <Sidebar />           
          </div>
          <header className="flex justify-end items-center p-0 gap-4 pt-3">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
            </SignedIn>
          </header>

          {/* Add top padding to offset the fixed navbar */}
            <main className="pt-16">
              {children}
            </main>
        </body>
      </html>
      </ThemeProvider>
    </ClerkProvider>
  )
}
